// Generated by Haxe 4.2.0-rc.1+64bbaabab
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IEquatable
{
	boolean equals(java.lang.Object to);
	
}


