// Generated by Haxe 4.2.0-rc.1+36263b392
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		haxe.root.Main.main();
	}
	
	public Main(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Main()
	{
		//line 5 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Main.__hx_ctor__Main(this);
	}
	
	
	protected static void __hx_ctor__Main(haxe.root.Main __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 8 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-2147450880) ), ((java.lang.Object) (-2147450880) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (8) )) )})) ));
		//line 8 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 9 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-2147450881) ), ((java.lang.Object) (-2147450881) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (9) )) )})) ));
		//line 9 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr2 = ((java.lang.Object) (null) );
		//line 10 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-1) ), ((java.lang.Object) (-1) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (10) )) )})) ));
		//line 10 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr3 = ((java.lang.Object) (null) );
		//line 11 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (2147483647) ), ((java.lang.Object) (2147483647) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (11) )) )})) ));
		//line 11 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr4 = ((java.lang.Object) (null) );
		//line 12 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (1073741823) ), ((java.lang.Object) (1073741823) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (12) )) )})) ));
		//line 12 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr5 = ((java.lang.Object) (null) );
		//line 13 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-2147483648) ), ((java.lang.Object) (-2147483648) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (13) )) )})) ));
		//line 13 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr6 = ((java.lang.Object) (null) );
		//line 14 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-1073741824) ), ((java.lang.Object) (-1073741824) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (14) )) )})) ));
		//line 14 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr7 = ((java.lang.Object) (null) );
		//line 15 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.writePair(((java.lang.Object) (-536870912) ), ((java.lang.Object) (-536870912) ), ((java.lang.Object) (new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (15) )) )})) ));
		//line 15 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		java.lang.Object __temp_expr8 = ((java.lang.Object) (null) );
		//line 16 "C:\\haxe issues\\haxe-integer-reporter\\Main.hx"
		haxe.root.Writer.close();
	}
	
	
}


