// Generated by Haxe 4.2.0-rc.1+e6d21742f
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Macros extends haxe.lang.HxObject
{
	public Macros(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Macros()
	{
		//line 18 "J:\\b.e\\haxe-integer-reporter\\Macros.hx"
		haxe.root.Macros.__hx_ctor__Macros(this);
	}
	
	
	protected static void __hx_ctor__Macros(haxe.root.Macros __hx_this)
	{
	}
	
	
}


